### ISSUE TITLE
No need for symbols here.

### ISSUE THREAD

**Issue by IngusSkaistkalns** [liepauls/carefully#1]
https://github.com/liepauls/safe_delete/blob/master/lib/safe_delete.rb#L61

**Comment by liepauls** [comment]
Theoretically, yes, but
  1. symbols look prettier (IMO)
  2. since this option is configurable, I need to `.map(&:to_s)` before checking if it includes current environment, as some users might write symbols, but others strings

**Comment by IngusSkaistkalns** [comment]
`as some users might write symbols, but others strings` - i was talking only about Rails.env - that will always be string. 

But ok, go for the prettier...
