### ISSUE TITLE
Class methods #destroy #delete are missed

### ISSUE THREAD

**Issue by IngusSkaistkalns** [liepauls/carefully#3]
https://api.rubyonrails.org/classes/ActiveRecord/Associations/CollectionProxy.html#method-i-delete

**Comment by liepauls** [comment]
`#destroy` calls `object.destroy`, but thanks for the `#delete`!

**Comment by liepauls** [comment]
Fixed in https://github.com/liepauls/carefully/commit/2e4067acc69fb9f519c427b389a5a4d6db7b8fee
