### ISSUE TITLE
Do not include in AR::Base by default please

### ISSUE THREAD

**Issue by IngusSkaistkalns** [liepauls/carefully#5]
https://github.com/liepauls/safe_delete/blob/master/lib/generators/safe_delete.rb#L12

leave that decision upon developer. We also have ApplicationRecord, there is also possibility just to guard few models in case of include per model.

**Comment by liepauls** [comment]
Fixed in https://github.com/liepauls/carefully/commit/ca2d6c026757797f8faa4de48f85d72a21ad2627
